# Generated by Django 4.1.1 on 2022-10-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='contenet',
            new_name='content',
        ),
    ]
