# Generated by Django 4.1.1 on 2022-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(blank=True, default='holder.jpg', null=True, upload_to='post_images'),
        ),
    ]
