# Generated by Django 4.1.1 on 2022-10-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posts_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
